### ISSUE TITLE
Install zsh and mediainfo packages

### ISSUE THREAD

**Issue by donegaci** [sigmedia/linux-servers-bootstrap#11]

**Comment by seblemaguer** [comment]
zsh is already part of the installed packages (by default but I need to think about an update process with "user space" packages).  I will add mediainfo. For which machine do you need it in priority?

**Comment by donegaci** [comment]
sig204, thanks!

**Comment by seblemaguer** [comment]
fixed in 65ab61acf397d686921337e7d549c8776f6f178c
